/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MgvReaderInterface extends ethers.utils.Interface {
  functions: {
    "book(address,address,uint256)": FunctionFragment;
    "packed_book(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "book",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "packed_book",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "book", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packed_book",
    data: BytesLike
  ): Result;

  events: {};
}

export class MgvReader extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MgvReaderInterface;

  functions: {
    book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber[],
        ([BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
          prev: BigNumber;
          next: BigNumber;
          gives: BigNumber;
          wants: BigNumber;
          gasprice: BigNumber;
        })[],
        ([string, BigNumber, BigNumber, BigNumber] & {
          maker: string;
          gasreq: BigNumber;
          overhead_gasbase: BigNumber;
          offer_gasbase: BigNumber;
        })[]
      ]
    >;

    packed_book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], string[], string[]]>;
  };

  book(
    base: string,
    quote: string,
    num_offers: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber[],
      ([BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        prev: BigNumber;
        next: BigNumber;
        gives: BigNumber;
        wants: BigNumber;
        gasprice: BigNumber;
      })[],
      ([string, BigNumber, BigNumber, BigNumber] & {
        maker: string;
        gasreq: BigNumber;
        overhead_gasbase: BigNumber;
        offer_gasbase: BigNumber;
      })[]
    ]
  >;

  packed_book(
    base: string,
    quote: string,
    num_offers: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], string[], string[]]>;

  callStatic: {
    book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber[],
        ([BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
          prev: BigNumber;
          next: BigNumber;
          gives: BigNumber;
          wants: BigNumber;
          gasprice: BigNumber;
        })[],
        ([string, BigNumber, BigNumber, BigNumber] & {
          maker: string;
          gasreq: BigNumber;
          overhead_gasbase: BigNumber;
          offer_gasbase: BigNumber;
        })[]
      ]
    >;

    packed_book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], string[], string[]]>;
  };

  filters: {};

  estimateGas: {
    book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    packed_book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    packed_book(
      base: string,
      quote: string,
      num_offers: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
