/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MgvReader } from "./MgvReader";

export { MgvReader__factory } from "./factories/MgvReader__factory";
